name: Multi-Branch Deployment

on:
  push:
    branches:
      - main
      - develop
      - components
      - blog

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build UI Library
        run: pnpm --filter @abdalkader/ui build
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "🚀 Deploying Portfolio to Production (abdalkader.dev)"
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_PORTFOLIO }}" >> $GITHUB_ENV
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
            
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "🧪 Deploying Portfolio to Staging (dev.abdalkader.dev)"
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_STAGING }}" >> $GITHUB_ENV
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
            deployment_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
            vercel alias $deployment_url dev.abdalkader.dev --token=${{ secrets.VERCEL_TOKEN }}
            echo "✅ Staging deployment complete: https://dev.abdalkader.dev"
            
          elif [ "${{ github.ref }}" == "refs/heads/components" ]; then
            echo "📚 Deploying Storybook to components.abdalkader.dev"
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_STORYBOOK }}" >> $GITHUB_ENV
            cd apps/storybook
            pnpm build
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
            
          elif [ "${{ github.ref }}" == "refs/heads/blog" ]; then
            echo "📝 Deploying Blog"
            # Add blog deployment logic here
            
          fi
