name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI
        run: |
          npx lhci autorun --collect.staticDistDir=.next --assert.assertions.categories.performance=error --assert.assertions.categories.accessibility=error

